services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-default-use
    ports:
      - "9999:9999"
    command: start-notebook.sh --NotebookApp.port=9999 --NotebookApp.ip=0.0.0.0
    volumes:
      - ~/jupyter-data/work:/home/jovyan/work
      - app-data-default-use:/app/configs
    environment:
      - CHOWN_EXTRA="/home/jovyan/work"
      - CHOWN_EXTRA_OPTS="-R"
      - JUPYTER_ENABLE_LAB=no
      - JUPYTER_TOKEN=asktobianca
    restart: unless-stopped

volumes:
  app-data-default-use:
